baseURL: "https://ru.algorithmica.org/"
theme:
- algorithmica
- reveal-hugo
pygmentsUseClasses: true
outputFormats:
  Reveal:
    baseName: index
    mediaType: text/html
    isHTML: true
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true
outputs:
  home:
  - HTML
  - SearchIndex
markup:
  goldmark:
    footnote: false  # katex conflict
    renderer:
      unsafe: true
defaultContentLanguage: vi
sectionPagesMenu: main
languages:
  en:
    title: Algorithmica
    baseURL: https://en.algorithmica.org
    contentDir: content/english
    languageName: English
    languageCode: "en-us"
    weight: 1
  ru:
    title: Алгоритмика
    baseURL: https://ru.algorithmica.org
    contentDir: content/russian
    languageName: Русский
    languageCode: "ru-ru"
    weight: 2
  vi:
    title: Thuật toán hiệu năng cao cho phần cứng hiện đại
    baseURL: https://vi.algorithmica.org
    contentDir: content/vietnamese
    languageName: Tiếng Việt
    languageCode: "vi-vn"
    weight: 3
params:
  repo: "https://github.com/algorithmica-org/algorithmica"
  reveal_hugo:
    #theme: white
    slide_number: true
    transition: none
    custom_theme: "slides.sass"
    custom_theme_compile: true
